services:
  stress-test:
    container_name: pipeline-memory-stress-test
    build:
      context: .
      dockerfile: data_pipeline/Dockerfile

    # Mount the local data folder
    volumes:
      - ./data:/app/data

    # Provision Specs: Memory 8 Gb/ 2cpu/2 threads
    # Memory tax = Sandbox Tax +  Import Tax + I/O Buffer Tax
    # Max Data Size = (Total RAM- 8GB) - (Memory Tax - 1.5GB) = 6.5GB
    mem_limit: 6.5G
    memswap_limit: 6.5G
    cpus: '2.0'
    environment:
      - POLARS_MAX_THREADS=2
